### PR TITLE
Added CDC-Monitoring

### PR DESCRIPTION
**Pull request by Sumukh-Phalgaonkar**
CDC-Monitoring contains infra to setup Grafana dashboards using metrics collected from both YugabyteDB and Kafka-Connect.

### CODE REVIEW

**Review by vrajat — CHANGES_REQUESTED** [review]
Can you rename the directory to `monitoring` ? LGTM otherwise.

**Review by vrajat — CHANGES_REQUESTED** [review]
The directory structure looks good to me. Can you please address the comments I provided #1 ?

**Review by vrajat — CHANGES_REQUESTED** [review]
Can you separate kafka-connect into a separate yaml file and prometheus and Grafana into another file?

On second thoughts, this directory should only container docker compose files for monitoring only. Another example (different directory) can have docker compose files for Kafka and Kafka connect.
This repo to should show case the setup for prometheus and grafana.

**Comment by Sumukh-Phalgaonkar** [comment]
Hi, in the latest PR kafka-connect is being created in kafka-connect.yaml and all other containers are created in docker-compose.yaml, Do you want me to put kafka-connect.yaml in a separate directory?

**Comment by vrajat** [comment]
My request is to have only prometheus and grafana in docker compose and remove everything else. Instead of repeating the Kafka connect instructions, lets add a link in README on how to setup yb, Kafka and Kafka connect.

**Pull request closed without merging**
